### ISSUE TITLE
Cannot get values of Laser range finder

### ISSUE THREAD

**Issue by michele-colombo** [umdlife/psdk_ros2#138]
**Tell us about your environment**
Jetson Xavier NX, DJI M300 with H20 payload. ROS2 humble in docker.

* **Ubuntu version:** 22.04 (host is 20.04)
* **Docker Version:** 
* **ROS/ROS2 version:** Humble (with CycloneDDS)
* **Commit hash:** `b8f5721bcddfacdd83bab43b4b47a36c3fe49b49`

#### Steps to reproduce issue

Start the psdk. Communication is fine (I can read topics such as `position_fused`, `gimbal_angles` or successfully control the gimbal publishing on `gimbal_rotation`). If I try to read the distance measured by the laser range finder mounted on the payload with:
```shell
ros2 service call /wrapper/psdk_ros2/camera_get_laser_ranging_info psdk_interfaces/srv/CameraGetLaserRangingInfo "{payload_index: 1}"
```

#### Expected behavior
Read a distance of about 7.5 meters in the response to the service call.

#### Actual behavior

I always get `success=True`, but `distance=0`, even though I can read the correct distance (around 7.5 m) on the remote controller. The complete response is: `psdk_interfaces.srv.CameraGetLaserRangingInfo_Response(success=True, longitude=0.0, latitude=0.0, altitude=0, distance=0, screen_x=0, screen_y=0, enable_lidar=False, exception=0)`
I tried with payload_index 2 or 3, but in that case I get `success=False`

#### Additional information

The mandatory module section in `psdk_params.yaml` is set like this:
```yaml
      mandatory_modules:
        telemetry: true
        flight_control: true
        camera: true
        gimbal: true
        liveview: true
        hms: false
        perception: true
```
